services:
  app:
    container_name: inventory-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: pnpm run dev
    depends_on:
      - db

  db:
    container_name: inventory-db
    image: postgres:15
    restart: always
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
