services:
  nginx:
    image: nginx:latest
    container_name: inventory-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  app:
    container_name: inventory-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "1234:5000"
    volumes:
      - .:/app
    command: pnpm run dev
    depends_on:
      - postgres
      - mysql
      - mongo

  postgres:
    container_name: inventory-postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    container_name: inventory-mysql
    image: mysql:8
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysqldata:/var/lib/mysql

  mongo:
    container_name: inventory-mongo
    image: mongo:7.0
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mysqldata:
  mongodata:
